### ISSUE TITLE
개발단계 전 회의

### ISSUE THREAD

**Issue by fpdjsns** [DoPinet/sacheonSeong#10]
**회의 필요한 이슈**
* [ ] 사천성 블럭을 어떻게 구성할지에 대한 설계 
* [x] 프로젝트 세팅 (Vue.js) - 각자 세팅할 경우 merge 할 때 많은 충돌 예상
* [x] 프로젝트 폴더 구성 회의 

위 3가지 이슈가 해결되서 프로젝트 세팅과 블럭 및 공통적으로 사용할 클래스 or 구조체가 develop 브랜치에 push 한 뒤에 각자 개발이 가능.
프로젝트 폴더 세팅까지 끝낸 후 develop에 PR

**Comment by fpdjsns** [comment]
@DoPinet/dopi 
이 외에 추가로 필요한 안건 있으면 추가해주세영.
회의 언제 할지도 정해야 합니다.

**Comment by vinus322** [comment]
전체 아키 설계는 같이하고 세부는 각자 설계 해야될듯
Vue.js 스타트 페이지는 한사람이 만들고 푸쉬하자

**Comment by fpdjsns** [comment]
@vinus322 ㅇㅇ 좋아. 좋아.
전체 아키 설계가 어디까지인지는 각자 생각 좀 다를 수 있을테니 회의시간때 같이 정하면 될 듯!

**Comment by fpdjsns** [comment]
* [ ] 프로젝트 폴더 구성 회의 

프로젝트 폴더 세팅까지 끝낸 후 develop에 PR

**Comment by fpdjsns** [comment]
# 폴더 구조

- src
  - assests 
     - js (theme.js (게임 외적. 보조 기능), bootstrap (?) 요런거)
     - css (공통.css, A.css (파일 direct))
     - imges
  - views (게임.vue - 점수, 게임)
  - gameLogic (기능A.js)
  - components
       - componentA (html, vue, js (vue 관련))
  - App.vue
  - main.js

**Comment by fpdjsns** [comment]
## Resolve
- 프로젝트 세팅 (Vue.js) - 각자 세팅할 경우 merge 할 때 많은 충돌 예상
- 프로젝트 폴더 구성 회의

위 2가지 이슈 해결.
develop에 push.

## TODO
- 사천성 블럭을 어떻게 구성할지에 대한 설계

1/25 (금) PM 10시 - 회의 (일정 변경될 수 있음)
